# Generated by Django 4.2.1 on 2023-06-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=10, unique=True)),
                ('examname', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty', models.CharField(max_length=500, null=True)),
                ('seats', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('examid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setexam.examid')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=50)),
                ('seat_row', models.IntegerField()),
                ('seat_column', models.IntegerField()),
                ('examid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setexam.examid')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setexam.section')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=500)),
                ('branch_name', models.CharField(max_length=500)),
                ('exam_name', models.CharField(max_length=500, null=True)),
                ('exam_time', models.CharField(max_length=500, null=True)),
                ('csv_file_path', models.FileField(null=True, upload_to='uploaded')),
                ('examid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setexam.examid')),
            ],
        ),
    ]
