# Generated by Django 4.2.1 on 2023-06-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_id", models.CharField(max_length=10, unique=True)),
                ("examname", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "class_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("seats", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=50)),
                ("branch_name", models.CharField(max_length=200)),
                ("exam_name", models.CharField(max_length=200, null=True)),
                ("exam_time", models.CharField(max_length=200, null=True)),
                ("csv_file_path", models.FileField(null=True, upload_to="uploaded")),
                (
                    "examid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setexam.examid",
                    ),
                ),
            ],
        ),
    ]
