# Generated by Django 4.2.1 on 2023-06-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setexam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="branch_name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="batch",
            name="exam_name",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="exam_time",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="year",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="examid",
            name="examname",
            field=models.CharField(max_length=500),
        ),
    ]
