# Generated by Django 4.2.1 on 2023-06-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setexam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='faculty',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
