# Generated by Django 4.2.1 on 2023-06-03 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setexam', '0002_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='yearexam',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='yearexam',
            name='year',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='year_exam',
        ),
        migrations.RemoveField(
            model_name='year',
            name='exams',
        ),
        migrations.AddField(
            model_name='batch',
            name='year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setexam.year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.DeleteModel(
            name='YearExam',
        ),
        migrations.AddField(
            model_name='uploadedcsv',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setexam.batch'),
        ),
        migrations.AddField(
            model_name='uploadedcsv',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setexam.exam'),
        ),
        migrations.AddField(
            model_name='uploadedcsv',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setexam.year'),
        ),
    ]
