# Generated by Django 4.2.1 on 2023-06-13 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("setexam", "0002_alter_batch_branch_name_alter_batch_exam_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="examid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="setexam.examid",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="faculty",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
