# Generated by Django 4.2.1 on 2023-06-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setexam", "0003_section_examid_section_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="class_id",
            field=models.PositiveIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
