# Generated by Django 4.2.1 on 2023-06-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setexam", "0004_alter_section_class_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="seats",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
