# Generated by Django 4.2.1 on 2023-06-03 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_faculty_facultyname'),
        ('setexam', '0004_allotment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.faculty', to_field='FacultyName'),
        ),
    ]
