# Generated by Django 4.2.1 on 2023-06-03 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_faculty_facultyname'),
        ('setexam', '0005_alter_allotment_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='login.faculty', to_field='FacultyName'),
        ),
    ]
