# Generated by Django 4.1.7 on 2023-06-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setexam", "0005_alter_section_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="seats",
            field=models.TextField(blank=True, null=True),
        ),
    ]
