# Generated by Django 4.2.1 on 2023-06-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_faculty_facultyname'),
        ('setexam', '0006_alter_allotment_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='allotment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.faculty', to_field='FacultyName'),
        ),
        migrations.CreateModel(
            name='ClassAllotted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('csv_file', models.FileField(upload_to='csv_file/')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allotted', to='setexam.exam')),
            ],
        ),
    ]
