# Generated by Django 4.1.7 on 2023-06-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setexam", "0006_alter_section_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="file_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
