# Generated by Django 4.2.1 on 2023-06-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setexam', '0007_examid_alter_allotment_faculty_classallotted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classallotted',
            name='exam',
        ),
        migrations.AddField(
            model_name='classallotted',
            name='exam_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='class_allotted', to='setexam.examid'),
            preserve_default=False,
        ),
    ]
