# Generated by Django 4.2.1 on 2023-06-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setexam', '0008_remove_classallotted_exam_classallotted_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classallotted',
            name='classallotted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
