# Generated by Django 4.2.1 on 2023-06-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("setexam", "0008_student"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
