# Generated by Django 4.2.1 on 2023-06-04 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setexam', '0009_classallotted_classallotted'),
    ]

    operations = [
        migrations.AddField(
            model_name='examid',
            name='examdate',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 13, 7, 11, 735247, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examid',
            name='examname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examid',
            name='examtime',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
