# Generated by Django 4.2.1 on 2023-06-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("setexam", "0010_alter_section_class_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("batch", models.CharField(max_length=50)),
                ("seat_row", models.IntegerField()),
                ("seat_column", models.IntegerField()),
                (
                    "examid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setexam.examid",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setexam.section",
                    ),
                ),
            ],
        ),
    ]
