# Generated by Django 4.2.1 on 2023-06-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_faculty_facultyname'),
        ('setexam', '0010_examid_examdate_examid_examname_examid_examtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classallotted',
            name='faculty_assigned',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.faculty'),
        ),
    ]
