# Generated by Django 4.2.1 on 2023-06-06 00:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setexam", "0011_alter_classallotted_faculty_assigned"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                ("class_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "section_data",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=100), size=None
                        ),
                        size=None,
                    ),
                ),
            ],
        ),
    ]
