# Generated by Django 4.2.1 on 2023-06-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setexam", "0012_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="section_data",
        ),
        migrations.AddField(
            model_name="section",
            name="seats",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="class_id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="ClassAllotted",
        ),
    ]
