# Generated by Django 4.1.7 on 2023-06-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setexam", "0013_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="class_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="faculty",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
