# Generated by Django 4.2.1 on 2023-05-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='malpractice',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=500)),
                ('StudentRegister', models.CharField(max_length=500)),
                ('StudentClass', models.CharField(max_length=500)),
                ('StudentBatch', models.CharField(max_length=500)),
                ('StudentInvigilator', models.CharField(max_length=500)),
                ('StudentRemark', models.CharField(max_length=500)),
            ],
        ),
    ]
