# Generated by Django 4.2.1 on 2023-05-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malpractice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malpractice',
            name='StudentRegister',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
