# Generated by Django 4.2.1 on 2023-06-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malpractice', '0002_alter_malpractice_studentregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malpractice',
            name='StudentBatch',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='malpractice',
            name='StudentClass',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='malpractice',
            name='StudentName',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
