# Generated by Django 4.2.1 on 2023-06-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malpractice', '0003_alter_malpractice_studentbatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malpractice',
            name='StudentBatch',
        ),
        migrations.RemoveField(
            model_name='malpractice',
            name='StudentClass',
        ),
        migrations.RemoveField(
            model_name='malpractice',
            name='StudentName',
        ),
    ]
