# Generated by Django 4.2.1 on 2023-05-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('FacultyId', models.AutoField(primary_key=True, serialize=False)),
                ('FacultyName', models.CharField(max_length=500)),
                ('FacultyPass', models.CharField(max_length=500)),
                ('FacultyEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
